import { MediaItem, Genre } from '../types';

export const GENRES: Genre[] = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Adventure' },
  { id: 16, name: 'Animation' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 99, name: 'Documentary' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Family' },
  { id: 14, name: 'Fantasy' },
  { id: 36, name: 'History' },
  { id: 27, name: 'Horror' },
  { id: 10402, name: 'Music' },
  { id: 9648, name: 'Mystery' },
  { id: 10749, name: 'Romance' },
  { id: 878, name: 'Sci-Fi' },
  { id: 53, name: 'Thriller' },
  { id: 10752, name: 'War' },
  { id: 10765, name: 'Sci-Fi & Fantasy' },
  { id: 10759, name: 'Action & Adventure' },
];

export const CURATED_MEDIA: MediaItem[] = [
  {
    id: 101,
    title: 'Special Ops: Lioness',
    name: 'Special Ops: Lioness',
    overview: 'Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA’s Lioness Engagement Team to help bring down a terrorist organization from within.',
    poster_path: '/7WUHnWGx5OO145IRxPDUkQ049da.jpg',
    backdrop_path: '/jWXrQstj7p9Wxd9viKxduW0bKa.jpg',
    vote_average: 8.2,
    vote_count: 2450,
    release_date: '2024-10-27',
    media_type: 'tv',
    genre_ids: [18, 10759, 80],
    runtime: 55,
    number_of_seasons: 2,
    number_of_episodes: 16,
    tagline: 'Undercover. Infiltration. No way out.',
    trailer_key: 'hI5K8wQv_Ww',
    popularity: 940.5,
    cast: [
      { id: 1, name: 'Zoe Saldaña', character: 'Joe', profile_path: '/vQBwmsSOAd0JDaCrZ98TC09JSNm.jpg' },
      { id: 2, name: 'Laysla De Oliveira', character: 'Cruz Manuelos', profile_path: '/6qBuh8B3L2Z60kI3QoB06h1b76x.jpg' },
      { id: 3, name: 'Nicole Kidman', character: 'Kaitlyn Meade', profile_path: '/w7iZ2b04B3u7eC9QjKxH96r1k.jpg' },
      { id: 4, name: 'Morgan Freeman', character: 'Edwin Mullins', profile_path: '/jPsLqiYGSofU4s6BjrxnefMfabb.jpg' }
    ]
  },
  {
    id: 102,
    title: 'The Last House',
    name: 'The Last House',
    overview: 'A secluded family homestead harbors dark secrets when unexpected visitors seek refuge during a catastrophic paranormal blackout in the surrounding forest.',
    poster_path: '/e1Xq6tPvhZ605oU4e2rLzZp6p6M.jpg',
    backdrop_path: '/m4qZwLd8u10uIe8v5kY3m4X90p.jpg',
    vote_average: 6.9,
    vote_count: 830,
    release_date: '2026-02-14',
    media_type: 'movie',
    genre_ids: [27, 9648, 53],
    runtime: 104,
    tagline: 'Lock the doors. Do not look outside.',
    trailer_key: 'b9EkMc79ZSU',
    popularity: 780.2,
    cast: [
      { id: 11, name: 'Ethan Hawke', character: 'Arthur Blake', profile_path: '/21T1cQ2r3J1Y1G4r9Q8k2k0m.jpg' },
      { id: 12, name: 'Gemma Chan', character: 'Elena Ward', profile_path: '/rE59k6Z3qP9k1u7G8k2k0m.jpg' }
    ]
  },
  {
    id: 103,
    title: 'Minions & Monsters',
    name: 'Minions & Monsters',
    overview: 'When an eccentric laboratory experiment goes awry, the Minions accidentally unleash friendly alien critters into the metropolis, sparking a hilariously chaotic rescue mission.',
    poster_path: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
    backdrop_path: '/lgkGYSgBw41mUe7f8M76M59m.jpg',
    vote_average: 7.5,
    vote_count: 3120,
    release_date: '2026-05-18',
    media_type: 'movie',
    genre_ids: [16, 35, 10751, 12],
    runtime: 98,
    tagline: 'Chaos has never looked so yellow.',
    trailer_key: '6DxjJzmYsXo',
    popularity: 1120.4,
    cast: [
      { id: 21, name: 'Pierre Coffin', character: 'Kevin / Stuart / Bob (voice)', profile_path: '/5D4B2qB7Xq0rZ0V.jpg' },
      { id: 22, name: 'Steve Carell', character: 'Gru (voice)', profile_path: '/dzJtsLspI5My6al9tdEzW01h.jpg' }
    ]
  },
  {
    id: 104,
    title: 'Rage',
    name: 'Rage',
    overview: 'An elite tactical driver is thrust into a deadly race against the clock across desolate borderlands to rescue an abducted operative before nightfall.',
    poster_path: '/9GBhzXMFNTgcGHetio2v11V0H0.jpg',
    backdrop_path: '/8pkrh3FjF0o4gYt3L0e9dK2o1.jpg',
    vote_average: 7.1,
    vote_count: 950,
    release_date: '2026-01-20',
    media_type: 'movie',
    genre_ids: [28, 53, 80],
    runtime: 112,
    tagline: 'Velocity is his only weapon.',
    trailer_key: 'd96cjJhvlMA',
    popularity: 640.0,
    cast: [
      { id: 31, name: 'Karl Urban', character: 'Vance Stone', profile_path: '/jJmG3M0P1Y0V8q1.jpg' }
    ]
  },
  {
    id: 105,
    title: 'Dune: Part Two',
    name: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s5hj0x2.jpg',
    vote_average: 8.6,
    vote_count: 6150,
    release_date: '2024-03-01',
    media_type: 'movie',
    genre_ids: [878, 12, 18],
    runtime: 166,
    tagline: 'Long live the fighters.',
    trailer_key: 'Way9Dexny3w',
    popularity: 1850.8,
    cast: [
      { id: 41, name: 'Timothée Chalamet', character: 'Paul Atreides', profile_path: '/BE2sdjpgEV2rNTFaUQ7A.jpg' },
      { id: 42, name: 'Zendaya', character: 'Chani', profile_path: '/r2ee0B28p1B7yZ.jpg' },
      { id: 43, name: 'Rebecca Ferguson', character: 'Lady Jessica', profile_path: '/4z19T10C1b80.jpg' },
      { id: 44, name: 'Austin Butler', character: 'Feyd-Rautha Harkonnen', profile_path: '/8qV12G.jpg' }
    ]
  },
  {
    id: 106,
    title: 'Deadpool & Wolverine',
    name: 'Deadpool & Wolverine',
    overview: 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary behind him. But when his homeworld faces an existential threat, he must suit up again.',
    poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdrop_path: '/yD37ehKx097q7J8r86Y0eZ6.jpg',
    vote_average: 7.8,
    vote_count: 5800,
    release_date: '2024-07-26',
    media_type: 'movie',
    genre_ids: [28, 35, 878],
    runtime: 128,
    tagline: 'Everyone deserves a happy ending.',
    trailer_key: '73_1biulkYk',
    popularity: 1620.0,
    cast: [
      { id: 51, name: 'Ryan Reynolds', character: 'Wade Wilson / Deadpool', profile_path: '/4SYTH5F.jpg' },
      { id: 52, name: 'Hugh Jackman', character: 'Logan / Wolverine', profile_path: '/4xX410J.jpg' },
      { id: 53, name: 'Emma Corrin', character: 'Cassandra Nova', profile_path: '/98xW12.jpg' }
    ]
  },
  {
    id: 107,
    title: 'Gladiator II',
    name: 'Gladiator II',
    overview: 'Years after witnessing the death of revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome.',
    poster_path: '/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdrop_path: '/euYIwmwkmz95mnExrOoEx0M2.jpg',
    vote_average: 7.2,
    vote_count: 3200,
    release_date: '2024-11-22',
    media_type: 'movie',
    genre_ids: [28, 12, 18],
    runtime: 148,
    tagline: 'What we do in life echoes in eternity.',
    trailer_key: '4rgYUipGJNo',
    popularity: 1410.0,
    cast: [
      { id: 61, name: 'Paul Mescal', character: 'Lucius', profile_path: '/3uY4R9e.jpg' },
      { id: 62, name: 'Pedro Pascal', character: 'Marcus Acacius', profile_path: '/9m1r0u.jpg' },
      { id: 63, name: 'Denzel Washington', character: 'Macrinus', profile_path: '/8qR9e.jpg' }
    ]
  },
  {
    id: 108,
    title: 'Severance',
    name: 'Severance',
    overview: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears, it begins a journey to uncover the truth.',
    poster_path: '/p6WvdZ0t8b5xVb0a9uE2qM1p.jpg',
    backdrop_path: '/r2t6Vw0lP8K3o2q0L1V9y.jpg',
    vote_average: 8.8,
    vote_count: 4200,
    release_date: '2022-02-18',
    media_type: 'tv',
    genre_ids: [18, 9648, 878],
    runtime: 52,
    number_of_seasons: 2,
    number_of_episodes: 19,
    tagline: 'Please do not attempt to remember your life.',
    trailer_key: 'xEQP4VVuyrY',
    popularity: 1540.0,
    cast: [
      { id: 71, name: 'Adam Scott', character: 'Mark Scout', profile_path: '/1bV8.jpg' },
      { id: 72, name: 'Patricia Arquette', character: 'Harmony Cobel', profile_path: '/2bV8.jpg' },
      { id: 73, name: 'John Turturro', character: 'Irving Bailiff', profile_path: '/3bV8.jpg' },
      { id: 74, name: 'Christopher Walken', character: 'Burt Goodman', profile_path: '/4bV8.jpg' }
    ]
  },
  {
    id: 109,
    title: 'Arcane',
    name: 'Arcane',
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    poster_path: '/fqldf2t8ztc9aiwn396nlvupn.jpg',
    backdrop_path: '/a6b0c2d3e4f5g6h7i8j9.jpg',
    vote_average: 9.0,
    vote_count: 6700,
    release_date: '2021-11-06',
    media_type: 'tv',
    genre_ids: [16, 10765, 10759, 18],
    runtime: 42,
    number_of_seasons: 2,
    number_of_episodes: 18,
    tagline: 'Every legend has a beginning.',
    trailer_key: 'fXmAurh012s',
    popularity: 1980.0,
    cast: [
      { id: 81, name: 'Hailee Steinfeld', character: 'Vi (voice)', profile_path: '/5bV8.jpg' },
      { id: 82, name: 'Ella Purnell', character: 'Jinx (voice)', profile_path: '/6bV8.jpg' }
    ]
  },
  {
    id: 110,
    title: 'The Last of Us',
    name: 'The Last of Us',
    overview: 'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.',
    poster_path: '/uKvVjHNqB5VmOrdxqAt2V7J.jpg',
    backdrop_path: '/1b2c3d4e5f6g7h8i9j0k.jpg',
    vote_average: 8.9,
    vote_count: 5900,
    release_date: '2023-01-15',
    media_type: 'tv',
    genre_ids: [18, 10759, 10765],
    runtime: 60,
    number_of_seasons: 2,
    number_of_episodes: 16,
    tagline: 'When you\'re lost in the darkness, look for the light.',
    trailer_key: 'uLtkt8BonwM',
    popularity: 1720.0,
    cast: [
      { id: 91, name: 'Pedro Pascal', character: 'Joel Miller', profile_path: '/9m1r0u.jpg' },
      { id: 92, name: 'Bella Ramsey', character: 'Ellie Williams', profile_path: '/7bV8.jpg' }
    ]
  },
  {
    id: 111,
    title: 'Interstellar',
    name: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xJHokMbljvjADYdit5fK5VzT.jpg',
    vote_average: 8.4,
    vote_count: 36000,
    release_date: '2014-11-05',
    media_type: 'movie',
    genre_ids: [12, 18, 878],
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    trailer_key: 'zSWdZVtXT7E',
    popularity: 1350.0,
    cast: [
      { id: 101, name: 'Matthew McConaughey', character: 'Joseph Cooper', profile_path: '/1a.jpg' },
      { id: 102, name: 'Anne Hathaway', character: 'Dr. Amelia Brand', profile_path: '/2a.jpg' },
      { id: 103, name: 'Jessica Chastain', character: 'Murphy Cooper', profile_path: '/3a.jpg' }
    ]
  },
  {
    id: 112,
    title: 'Moana 2',
    name: 'Moana 2',
    overview: 'After receiving an unexpected call from her wayfinding ancestors, Moana journeys to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she has ever faced.',
    poster_path: '/aLVkiAOAba66g4Xw0nF6.jpg',
    backdrop_path: '/tElnmt96asBHwb1.jpg',
    vote_average: 7.3,
    vote_count: 2100,
    release_date: '2024-11-27',
    media_type: 'movie',
    genre_ids: [16, 12, 10751, 35, 10402],
    runtime: 100,
    tagline: 'The ocean is calling her back.',
    trailer_key: 'hDZ7y8RP5HE',
    popularity: 1250.0,
    cast: [
      { id: 111, name: 'Auli\'i Cravalho', character: 'Moana (voice)', profile_path: '/4a.jpg' },
      { id: 112, name: 'Dwayne Johnson', character: 'Maui (voice)', profile_path: '/5a.jpg' }
    ]
  },
  {
    id: 113,
    title: 'Oppenheimer',
    name: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/rLb2cwF3Pazuxaj0sytQ3.jpg',
    vote_average: 8.1,
    vote_count: 9400,
    release_date: '2023-07-21',
    media_type: 'movie',
    genre_ids: [18, 36],
    runtime: 180,
    tagline: 'The world forever changes.',
    trailer_key: 'uYPbbksJxIg',
    popularity: 1100.0,
    cast: [
      { id: 121, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profile_path: '/6a.jpg' },
      { id: 122, name: 'Emily Blunt', character: 'Katherine Oppenheimer', profile_path: '/7a.jpg' },
      { id: 123, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profile_path: '/8a.jpg' }
    ]
  },
  {
    id: 114,
    title: 'Stranger Things',
    name: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdrop_path: '/56v2KjBlU4XaOv9rVYkjuypk.jpg',
    vote_average: 8.6,
    vote_count: 17200,
    release_date: '2016-07-15',
    media_type: 'tv',
    genre_ids: [10765, 18, 9648],
    runtime: 50,
    number_of_seasons: 5,
    number_of_episodes: 42,
    tagline: 'Every ending has a beginning.',
    trailer_key: 'b9EkMc79ZSU',
    popularity: 1450.0,
    cast: [
      { id: 131, name: 'Millie Bobby Brown', character: 'Eleven', profile_path: '/9a.jpg' },
      { id: 132, name: 'Finn Wolfhard', character: 'Mike Wheeler', profile_path: '/10a.jpg' },
      { id: 133, name: 'David Harbour', character: 'Jim Hopper', profile_path: '/11a.jpg' }
    ]
  },
  {
    id: 115,
    title: 'Spider-Man: Across the Spider-Verse',
    name: 'Spider-Man: Across the Spider-Verse',
    overview: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence.',
    poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdrop_path: '/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    vote_average: 8.4,
    vote_count: 7100,
    release_date: '2023-06-02',
    media_type: 'movie',
    genre_ids: [16, 28, 12, 878],
    runtime: 140,
    tagline: 'It\'s how you wear the mask that matters.',
    trailer_key: 'cqGjhVJWtEg',
    popularity: 1310.0,
    cast: [
      { id: 141, name: 'Shameik Moore', character: 'Miles Morales (voice)', profile_path: '/12a.jpg' },
      { id: 142, name: 'Hailee Steinfeld', character: 'Gwen Stacy (voice)', profile_path: '/13a.jpg' },
      { id: 143, name: 'Oscar Isaac', character: 'Miguel O\'Hara (voice)', profile_path: '/14a.jpg' }
    ]
  },
  {
    id: 116,
    title: 'Shōgun',
    name: 'Shōgun',
    overview: 'In Japan in the year 1600, at the dawn of a century-defining civil war, Lord Yoshii Toranaga is fighting for his life as his enemies on the Council of Regents unite against him.',
    poster_path: '/7O4iVfOMQmdCSPxXx1zK75Ywh.jpg',
    backdrop_path: '/2meX1nMdSc9OTzhT0hKU.jpg',
    vote_average: 8.7,
    vote_count: 2200,
    release_date: '2024-02-27',
    media_type: 'tv',
    genre_ids: [18, 10759, 10768],
    runtime: 58,
    number_of_seasons: 1,
    number_of_episodes: 10,
    tagline: 'Fate is a storm. Destiny is a choice.',
    trailer_key: 'yAN5uspAo8U',
    popularity: 1190.0,
    cast: [
      { id: 151, name: 'Hiroyuki Sanada', character: 'Lord Yoshii Toranaga', profile_path: '/15a.jpg' },
      { id: 152, name: 'Cosmo Jarvis', character: 'John Blackthorne', profile_path: '/16a.jpg' },
      { id: 153, name: 'Anna Sawai', character: 'Toda Mariko', profile_path: '/17a.jpg' }
    ]
  }
];

export const FALLBACK_BACKDROP = 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1600&auto=format&fit=crop&q=80';
export const FALLBACK_POSTER = 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80';
